### ISSUE TITLE
Naval Battle: calculate modifier based on target ship's class

### ISSUE THREAD

**Issue by evorios** [EaW1805/engine#16]
https://github.com/EaW1805/engine/blob/master/src/main/java/com/eaw1805/battles/naval/longrange/SOLLongRangeFire.java#L129

Here is code where function argument is wrong:

``` java
// Get target ship
final Ship targetShip;
...
// calculate modifier based on target ship's class
final int fireModShipClass = calcTargetFireModifier(ship.getType().getShipClass());
```

Must be:

``` java
// Get target ship
final Ship targetShip;
...
// calculate modifier based on target ship's class
final int fireModShipClass = calcTargetFireModifier(targetShip.getType().getShipClass());
```

The higher the class of the ship, the easier it is to hit it because it's big and clumsy. I'm right?

**Comment by ichatz** [comment]
Wow. Yes, that's correct. Made the fix on the engine's branch. I will merge with the public branch next week (along with many other minor fixes that were left behind due to limited time).
