### ISSUE TITLE
Random generator of Integer values

### ISSUE THREAD

**Issue by evorios** [EaW1805/engine#18]
I met a strange code, then I looked language documentation and realized that you have a serious mistake in several places. It usually looks like this:

``` java
// The ship will suffer an attrition of 1-2%
final int rndNum = getParent().getRandomGen().nextInt(1) + 1;
```

But [the official documentation](https://docs.oracle.com/javase/6/docs/api/java/util/Random.html#nextInt%28%29) says it is wrong to do so:

> `public int nextInt(int n)`
> Returns a pseudorandom, uniformly distributed int value between 0 (inclusive) and the specified value (**exclusive**), drawn from this random number generator's sequence.

**The result is that the variable `rndNum` is always strictly equal to 1.**

There is list of failed code:
[MountedArtilleryLongRangeCombat.java#L44](https://github.com/EaW1805/engine/blob/master/src/main/java/com/eaw1805/battles/tactical/longrange/MountedArtilleryLongRangeCombat.java#L44)
[TroopLongRangeCombat.java#L30](https://github.com/EaW1805/engine/blob/master/src/main/java/com/eaw1805/battles/tactical/longrange/TroopLongRangeCombat.java#L30)
[PositionChecker.java#L539](https://github.com/EaW1805/engine/blob/master/src/main/java/com/eaw1805/core/PositionChecker.java#L539)
[AbstractMovement.java#L1992](https://github.com/EaW1805/engine/blob/master/src/main/java/com/eaw1805/orders/movement/AbstractMovement.java#L1992)
[AbstractMovement.java#L2003](https://github.com/EaW1805/engine/blob/master/src/main/java/com/eaw1805/orders/movement/AbstractMovement.java#L2003)
[AbstractMovement.java#L2013](https://github.com/EaW1805/engine/blob/master/src/main/java/com/eaw1805/orders/movement/AbstractMovement.java#L2013)
[StormEvent.java](https://github.com/EaW1805/engine/blob/master/src/main/java/com/eaw1805/events/fleet/StormEvent.java) - ALL places where `nextInt()` used

There are other places where the use of a small random range may cause problems in the logic engine.

**Comment by Silver1974** [comment]
Hello Roman,

thank you for this finding, we will check it out asap! Keep up the good
work!

Cheers,
Makis

**Comment by Silver1974** [comment]
Hello Roman,

just to let you know that this issue is now fixed. Thank you for reporting!

Makis
